<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <IsPackable>false</IsPackable>
        <NeutralLanguage>en</NeutralLanguage>
        <RootNamespace>SimpleChdDrive.Core</RootNamespace>
        <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
        <DebugType>embedded</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>
        <NeutralLanguage>en</NeutralLanguage>
        <Company>PureLogicCode.com</Company>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="SimpleChdDrive" />
        <InternalsVisibleTo Include="SimpleChdDrive_WinFsp" />
        <InternalsVisibleTo Include="SimpleChdDrive.Core.Tests" />
        <InternalsVisibleTo Include="Tester" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\VideoGameFileSystemParser\VideoGameFileSystemParser.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Serilog" Version="4.4.0" />
        <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    </ItemGroup>

</Project>
