using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using Tester.Models;

namespace Tester.Services;

public sealed class PdfExportService
{
    static PdfExportService()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public void ExportToPdf(TestSummary summary, string outputPath)
    {
        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(30);
                page.DefaultTextStyle(x => x.FontFamily("Segoe UI").FontSize(10));

                page.Header().Element(c => ComposeHeader(c, summary));

                page.Content().Element(c => ComposeContent(c, summary));

                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated by Tester - ");
                    x.CurrentPageNumber();
                    x.Span(" / ");
                    x.TotalPages();
                });
            });
        }).GeneratePdf(outputPath);
    }

    private static void ComposeHeader(IContainer container, TestSummary summary)
    {
        container.Column(col =>
        {
            col.Item().Row(row =>
            {
                row.RelativeItem(2).PaddingTop(5).Text("CHD Parsing Test Report")
                    .FontSize(22).Bold().FontColor(Colors.Blue.Darken3);

                row.RelativeItem(1).PaddingTop(10).AlignRight()
                    .Text(DateTime.Now.ToString("yyyy-MM-dd HH:mm"))
                    .FontSize(10).FontColor(Colors.Grey.Medium);
            });

            col.Item().PaddingTop(8).LineHorizontal(2).LineColor(Colors.Blue.Darken2);

            col.Item().PaddingTop(20).Row(row =>
            {
                row.RelativeItem(1).PaddingRight(5).Column(c =>
                {
                    c.Item().Text("Console Type").FontSize(9).FontColor(Colors.Grey.Medium);
                    c.Item().Text(summary.ConsoleName).FontSize(14).Bold();
                });
                row.RelativeItem(1).Column(c =>
                {
                    c.Item().Text("Folder").FontSize(9).FontColor(Colors.Grey.Medium);
                    c.Item().Text(summary.ChdFolder).FontSize(14).Bold();
                });
            });

            col.Item().PaddingTop(8).Row(row =>
            {
                row.RelativeItem(1).Column(c =>
                {
                    c.Item().Text("Started").FontSize(9).FontColor(Colors.Grey.Medium);
                    c.Item().Text(summary.StartTime.ToString("yyyy-MM-dd HH:mm:ss")).FontSize(11);
                });
                row.RelativeItem(1).Column(c =>
                {
                    c.Item().Text("Completed").FontSize(9).FontColor(Colors.Grey.Medium);
                    c.Item().Text(summary.EndTime.ToString("yyyy-MM-dd HH:mm:ss")).FontSize(11);
                });
                row.RelativeItem(1).Column(c =>
                {
                    c.Item().Text("Duration").FontSize(9).FontColor(Colors.Grey.Medium);
                    c.Item().Text($"{summary.TotalDuration.TotalSeconds:F2}s").FontSize(11);
                });
            });
        });
    }

    private static void ComposeContent(IContainer container, TestSummary summary)
    {
        container.PaddingTop(25).Column(col =>
        {
            col.Item().PaddingBottom(15).Row(row =>
            {
                row.RelativeItem(1).PaddingRight(4).Element(StatBox(Colors.Blue.Darken2, "Total Files", summary.TotalFiles.ToString()));
                row.RelativeItem(1).PaddingLeft(2).PaddingRight(2).Element(StatBox(Colors.Green.Darken2, "Succeeded", summary.SuccessCount.ToString()));
                row.RelativeItem(1).PaddingLeft(2).PaddingRight(2).Element(StatBox(Colors.Red.Darken2, "Failed", summary.FailCount.ToString()));
                row.RelativeItem(1).PaddingLeft(2).PaddingRight(2).Element(StatBox(Colors.Orange.Darken2, "Avg Time", $"{summary.AverageDuration.TotalSeconds:F2}s"));
                row.RelativeItem(1).PaddingLeft(4).Element(StatBox(Colors.Purple.Darken2, "Total Size", FormatBytes((ulong)summary.TotalBytes)));
            });

            col.Item().PaddingBottom(8).Text("Test Results").FontSize(16).Bold().FontColor(Colors.Blue.Darken3);

            col.Item().Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(3);
                    columns.ConstantColumn(46);
                    columns.RelativeColumn(4);
                    columns.ConstantColumn(55);
                    columns.ConstantColumn(50);
                    columns.ConstantColumn(65);
                });

                table.Header(header =>
                {
                    var headerStyle = TextStyle.Default.FontSize(9).Bold().FontColor(Colors.White);
                    header.Cell().Background(Colors.Blue.Darken2).Padding(4).Text("File Name").Style(headerStyle);
                    header.Cell().Background(Colors.Blue.Darken2).Padding(4).AlignCenter().Text("Status").Style(headerStyle);
                    header.Cell().Background(Colors.Blue.Darken2).Padding(4).Text("Volume Name").Style(headerStyle);
                    header.Cell().Background(Colors.Blue.Darken2).Padding(4).AlignRight().Text("Size").Style(headerStyle);
                    header.Cell().Background(Colors.Blue.Darken2).Padding(4).AlignRight().Text("Items").Style(headerStyle);
                    header.Cell().Background(Colors.Blue.Darken2).Padding(4).AlignRight().Text("Duration").Style(headerStyle);
                });

                foreach (var result in summary.Results)
                {
                    var isSuccess = result.Success;
                    var bgColor = isSuccess ? Colors.White : Colors.Red.Lighten5;
                    var statusColor = isSuccess ? Colors.Green.Darken2 : Colors.Red.Darken2;
                    var statusText = isSuccess ? "OK" : "FAIL";
                    var rowStyle = TextStyle.Default.FontSize(9);

                    table.Cell().Background(bgColor).Padding(4).Text(result.FileName).Style(rowStyle);
                    table.Cell().Background(bgColor).Padding(4).AlignCenter()
                        .Text(statusText).FontColor(statusColor).Bold().Style(rowStyle);
                    table.Cell().Background(bgColor).Padding(4)
                        .Text(isSuccess ? result.VolumeName : result.ErrorMessage).Style(rowStyle);
                    table.Cell().Background(bgColor).Padding(4).AlignRight()
                        .Text(isSuccess ? FormatBytes(result.VolumeSize) : "-").Style(rowStyle);
                    table.Cell().Background(bgColor).Padding(4).AlignRight()
                        .Text(isSuccess ? (result.FileCount + result.DirectoryCount).ToString("N0") : "-").Style(rowStyle);
                    table.Cell().Background(bgColor).Padding(4).AlignRight()
                        .Text($"{result.Duration.TotalSeconds:F2}s").Style(rowStyle);
                }
            });

            if (summary.Fastest is not null || summary.Slowest is not null)
            {
                col.Item().PaddingTop(20).Text("Performance Data").FontSize(14).Bold().FontColor(Colors.Blue.Darken3);
                col.Item().PaddingTop(5).Row(row =>
                {
                    if (summary.Fastest is not null)
                        row.RelativeItem(1).Text($"Fastest: {summary.Fastest.FileName} ({summary.Fastest.Duration.TotalSeconds:F2}s)")
                            .FontSize(11);
                    if (summary.Slowest is not null)
                        row.RelativeItem(1).Text($"Slowest: {summary.Slowest.FileName} ({summary.Slowest.Duration.TotalSeconds:F2}s)")
                            .FontSize(11);
                    row.RelativeItem(1).Text($"Total Size: {FormatBytes((ulong)summary.TotalBytes)}").FontSize(11);
                });
            }
        });
    }

    private static Action<IContainer> StatBox(string color, string label, string value)
    {
        return container => container
            .Background(color)
            .Padding(6)
            .Column(inner =>
            {
                inner.Item().Text(label).FontSize(8).FontColor(Colors.White);
                inner.Item().Text(value).FontSize(14).Bold().FontColor(Colors.White);
            });
    }

    private static string FormatBytes(ulong bytes)
    {
        string[] sizes = ["B", "KB", "MB", "GB", "TB"];
        var order = 0;
        double size = bytes;
        while (size >= 1024 && order < sizes.Length - 1)
        {
            order++;
            size /= 1024;
        }
        return size == 0 ? "0 B" : $"{size:0.##} {sizes[order]}";
    }
}
